export const apartsVR = () => {
  return useState("apartsVR", () => {
    return {
      default: {
        firstScene: "room",
        author: "Veresk.club",
        sceneFadeDuration: 1000,
        autoRotate: 1,
        autoRotateInactivityDelay: 10000,
        autoLoad: true,
        compass: false,
        basePath: "/panoramas/apart/",
        hotSpotDebug: false,
      },
      scenes: {
        room: {
          title: "Первый этаж - кухня",
          hfov: 150,
          pitch: 3.349,
          yaw: -213.32,
          type: "equirectangular",
          panorama: "room.jpg",
          hotSpots: [
            {
              pitch: -3.082,
              yaw: -217.05,
              type: "scene",
              text: "Вход",
              sceneId: "door",
            },
            {
              pitch: -4.309,
              yaw: -201.54,
              type: "scene",
              text: "Ванная комната",
              sceneId: "bath",
            },
            {
              pitch: 5.3,
              yaw: -139.138,
              type: "scene",
              text: "Второй этаж",
              sceneId: "stairs",
            },
          ],
        },
        hall: {
          title: "Гостинная",
          hfov: 150,
          pitch: 3.349,
          yaw: -213.32,
          type: "equirectangular",
          panorama: "hall.jpg",
          hotSpots: [
            {
              pitch: -6.54,
              yaw: -103.14,
              type: "scene",
              text: "Лестница",
              sceneId: "stairs",
            },
          ],
        },
        bedroom: {
          title: "Спальня",
          hfov: 150,
          pitch: -14.234,
          yaw: -96.39,
          type: "equirectangular",
          panorama: "bedroom.jpg",
          hotSpots: [
            {
              pitch: -8.589,
              yaw: -249.16,
              type: "scene",
              text: "Лестница",
              sceneId: "stairs",
            },
            {
              pitch: -7.06,
              yaw: -86.48,
              type: "scene",
              text: "Балкон",
              sceneId: "balcony",
            },
          ],
        },
        door: {
          title: "Вход",
          hfov: 150,
          pitch: 7.163,
          yaw: 22.136,
          type: "equirectangular",
          panorama: "door.jpg",
          hotSpots: [
            {
              pitch: 8.434,
              yaw: 26.127,
              type: "scene",
              text: "Улица",
              sceneId: "mangal",
            },
            {
              pitch: 3.23,
              yaw: -100.82,
              type: "scene",
              text: "Первый этаж - кухня",
              sceneId: "room",
            },
          ],
        },
        balcony: {
          title: "Балкон",
          hfov: 150,
          pitch: -1.09,
          yaw: -33.463,
          type: "equirectangular",
          panorama: "balcony.jpg",
          hotSpots: [
            {
              pitch: -5.793,
              yaw: -232.29,
              type: "scene",
              text: "Спальная",
              sceneId: "bedroom",
            },
          ],
        },
        stairs: {
          title: "Второй этаж",
          hfov: 150,
          pitch: 6.14,
          yaw: -149.74,
          type: "equirectangular",
          panorama: "stairs.jpg",
          hotSpots: [
            {
              pitch: 1.069,
              yaw: -194.56,
              type: "scene",
              text: "Спальня",
              sceneId: "bedroom",
            },
            {
              pitch: -1.258,
              yaw: -139.15,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
            },
            {
              pitch: -1.09,
              yaw: -78.577,
              type: "scene",
              text: "Туалет",
              sceneId: "wc",
            },
            {
              pitch: -28.083,
              yaw: -261.12,
              type: "scene",
              text: "Первый этаж - Кухня",
              sceneId: "room",
            },
          ],
        },
        bath: {
          title: "Ванная комната",
          hfov: 150,
          pitch: 0.029,
          yaw: -165.499,
          type: "equirectangular",
          panorama: "bath.jpg",
          hotSpots: [
            {
              pitch: -4.04,
              yaw: -219.68,
              type: "scene",
              text: "Кухня",
              sceneId: "room",
            },
            {
              pitch: -1.734,
              yaw: -191.214,
              type: "scene",
              text: "Сауна",
              sceneId: "sauna",
            },
          ],
        },
        wc: {
          title: "Туалет",
          hfov: 150,
          pitch: 0.029,
          yaw: -165.499,
          type: "equirectangular",
          panorama: "wc.jpg",
          hotSpots: [
            {
              pitch: 0.1832,
              yaw: -205.26,
              type: "scene",
              text: "Лесница",
              sceneId: "stairs",
            },
          ],
        },
        sauna: {
          title: "Ванная комната",
          hfov: 150,
          pitch: 0.029,
          yaw: -165.499,
          type: "equirectangular",
          panorama: "sauna.jpg",
          hotSpots: [
            {
              pitch: -6.663,
              yaw: -138.354,
              type: "scene",
              text: "Ванная комната",
              sceneId: "bath",
            },
          ],
        },
        mangal: {
          title: "Ванная комната",
          hfov: 150,
          pitch: -4.217,
          yaw: 18.89,
          type: "equirectangular",
          panorama: "mangal.jpg",
          hotSpots: [
            {
              pitch: 8.434,
              yaw: -138.354,
              type: "scene",
              text: "Улица",
              sceneId: "mangal",
            },
            {
              pitch: 0.02,
              yaw: 106.582,
              type: "scene",
              text: "Прихожая",
              sceneId: "door",
            },
          ],
        },
      },
    };
  });
};
