export const dachiVR = () => {
  return useState("dachiVR", () => {
    return {
      default: {
        firstScene: "teastation",
        author: "Veresk.club",
        sceneFadeDuration: 1000,
        autoRotate: 1,
        autoRotateInactivityDelay: 10000,
        autoLoad: true,
        compass: false,
        basePath: "/panoramas/dacha/",
        // hotSpotDebug: false,
      },
      scenes: {
        hall: {
          title: "Гостинная",
          hfov: 150,
          pitch: -9.741,
          yaw: 12.911,
          type: "equirectangular",
          panorama: "hall.jpg",
          hotSpots: [
            {
              pitch: -1.45,
              yaw: -211.295,
              type: "scene",
              text: "Прихожая",
              sceneId: "lobby",
            },
            {
              pitch: -1.603,
              yaw: -163.0361,
              type: "scene",
              text: "Ванная комната",
              sceneId: "bath",
            },
            {
              pitch: -8.399,
              yaw: 25.86,
              type: "scene",
              text: "Терасса",
              sceneId: "balcony",
            },
            {
              pitch: -8.399,
              yaw: 73.193,
              type: "scene",
              text: "Спальня",
              sceneId: "bedroom",
            },
            {
              pitch: -3.874,
              yaw: -182.903,
              type: "scene",
              text: "Чайная станция",
              sceneId: "teastation",
            },
            {
              pitch: -24.709,
              yaw: -82.136,
              type: "scene",
              text: "ТВ Зона",
              sceneId: "tv",
            },
          ],
        },
        teastation: {
          title: "Чайная станция",
          hfov: 85,
          pitch: -3.164,
          yaw: 3.517,
          type: "equirectangular",
          panorama: "tea.jpg",
          hotSpots: [
            {
              pitch: -5.949,
              yaw: 356.42,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
              // "targetYaw": -23,
              // "targetPitch": 2
            },
            {
              pitch: -6.122,
              yaw: 313.103,
              type: "scene",
              text: "Ванная комната",
              sceneId: "bath",
            },
            {
              pitch: -4.593,
              yaw: 66.184,
              type: "scene",
              text: "Прихожая",
              sceneId: "lobby",
            },
          ],
        },
        tv: {
          title: "ТВ зона",
          hfov: 160,
          pitch: -0.839,
          yaw: -1.205,
          type: "equirectangular",
          panorama: "tv.jpg",
          hotSpots: [
            {
              pitch: -0.839,
              yaw: -1.205,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
              targetYaw: 0,
              targetPitch: 2,
            },
          ],
        },
        lobby: {
          title: "Прихожая",
          hfov: 180,
          pitch: -3,
          yaw: 220,
          type: "equirectangular",
          panorama: "door.jpg",
          hotSpots: [
            {
              pitch: -0.6,
              yaw: 78,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
              targetYaw: -23,
              targetPitch: 2,
            },
          ],
        },
        bedroom: {
          title: "Спальня",
          hfov: 120,
          pitch: -3,
          yaw: 350,
          type: "equirectangular",
          panorama: "bedroom.jpg",
          hotSpots: [
            {
              pitch: 2,
              yaw: 125,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
            },
          ],
        },
        sauna: {
          title: "Сауна",
          hfov: 180,
          pitch: -13.16,
          yaw: -7.524,
          type: "equirectangular",
          panorama: "sauna.jpg",
          hotSpots: [
            {
              pitch: -7.108,
              yaw: 13.152,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
              targetYaw: -23,
              targetPitch: 2,
            },
          ],
        },
        bath: {
          title: "Ванная комната",
          hfov: 120,
          pitch: -3,
          yaw: 350,
          type: "equirectangular",
          panorama: "bathroom.jpg",
          hotSpots: [
            {
              pitch: 1.209,
              yaw: -51.699,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
              targetYaw: -23,
              targetPitch: 2,
            },
            {
              pitch: 1.533,
              yaw: 34.975,
              type: "scene",
              text: "Сауна",
              sceneId: "sauna",
            },
          ],
        },
        balcony: {
          title: "Терасса",
          hfov: 120,
          pitch: 4,
          yaw: 180,
          type: "equirectangular",
          panorama: "balcony.jpg",
          hotSpots: [
            {
              pitch: -2.612,
              yaw: 180.539,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
            },
            {
              pitch: -12.455,
              yaw: 128.599,
              type: "scene",
              text: "Терасса - Зона отдыха",
              sceneId: "balcony-table",
            },
            {
              pitch: -14.08,
              yaw: 233.407,
              type: "scene",
              text: "Терасса - Зона отдыха",
              sceneId: "balcony-wooden",
            },
          ],
        },
        "balcony-table": {
          title: "Терасса - зона отдыха",
          hfov: 140,
          pitch: 5.452,
          yaw: 240.6,
          type: "equirectangular",
          panorama: "balcony_table.jpg",
          hotSpots: [
            {
              pitch: 4.341,
              yaw: 141.879,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
            },
            {
              pitch: 5.452,
              yaw: 240.6,
              type: "scene",
              text: "Терасса - основной вид",
              sceneId: "balcony",
              targetYaw: 175,
              targetPitch: -6,
            },
            {
              pitch: 16.701,
              yaw: 253.8,
              type: "scene",
              text: "Терасса - вид с улицы",
              sceneId: "balcony-out",
            },
          ],
        },
        "balcony-wooden": {
          title: "Терасса - зона отдыха",
          hfov: 140,
          pitch: 13.619,
          yaw: 154.035,
          type: "equirectangular",
          panorama: "balcony_wooden.jpg",
          hotSpots: [
            {
              pitch: 10.176,
              yaw: 233.497,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
            },
            {
              pitch: 13.619,
              yaw: 154.035,
              type: "scene",
              text: "Терасса - основной вид",
              sceneId: "balcony",
              targetYaw: 175,
              targetPitch: -6,
            },
            {
              pitch: 3.523,
              yaw: 210.51,
              type: "scene",
              text: "Терасса - зона отдыха",
              sceneId: "balcony-table",
            },
            {
              pitch: 19.655,
              yaw: 128.64,
              type: "scene",
              text: "Терасса - вид с улицы",
              sceneId: "balcony-out",
            },
          ],
        },
        "balcony-out": {
          title: "Терасса - вид с улицы",
          hfov: 140,
          pitch: -60.123,
          yaw: 174.006,
          type: "equirectangular",
          panorama: "outside.jpg",
          hotSpots: [
            {
              pitch: -56.827,
              yaw: 159.88,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
            },
            {
              pitch: -72.84,
              yaw: 98.826,
              type: "scene",
              text: "Терасса - основной вид",
              sceneId: "balcony",
            },
            {
              pitch: -46.758,
              yaw: 116.39,
              type: "scene",
              text: "Терасса - зона отдыха",
              sceneId: "balcony-table",
            },
            {
              pitch: -66.273,
              yaw: 223.184,
              type: "scene",
              text: "Терасса - зона отдыха",
              sceneId: "balcony-wooden",
            },
          ],
        },
      },
    };
  });
};
