export const hyggeVR = () => {
  return useState("hyggeVR", () => {
    return {
      default: {
        firstScene: "hall",
        author: "Veresk.club",
        sceneFadeDuration: 1000,
        autoRotate: 1,
        autoRotateInactivityDelay: 10000,
        autoLoad: true,
        compass: false,
        basePath: "/panoramas/hygge/",
        hotSpotDebug: false,
      },
      scenes: {
        hall: {
          title: "Кухня - Гостинная",
          hfov: 150,
          pitch: 3.349,
          yaw: -213.32,
          type: "equirectangular",
          panorama: "hall.jpg",
          hotSpots: [
            {
              pitch: -4.32,
              yaw: -310.931,
              type: "scene",
              text: "Вход",
              sceneId: "door",
            },
            {
              pitch: -14.4,
              yaw: -180.41,
              type: "scene",
              text: "Телевизор",
              sceneId: "tv",
            },
            {
              pitch: -7.748,
              yaw: -62.113,
              type: "scene",
              text: "Спальня",
              sceneId: "bedroom",
            },
            {
              pitch: -5.564,
              yaw: -123.41,
              type: "scene",
              text: "Веранда",
              sceneId: "balcony",
            },
          ],
        },
        tv: {
          title: "Кухня - Гостинная",
          hfov: 150,
          pitch: 3.349,
          yaw: -213.32,
          type: "equirectangular",
          panorama: "tv.jpg",
          hotSpots: [
            {
              pitch: 0.072,
              yaw: -161.81,
              type: "scene",
              text: "Вход",
              sceneId: "door",
            },
            {
              pitch: -1.33,
              yaw: -185.45,
              type: "scene",
              text: "Обеденный стол",
              sceneId: "hall",
            },
            {
              pitch: -5.196,
              yaw: -207.3,
              type: "scene",
              text: "Веранда",
              sceneId: "balcony",
            },
          ],
        },

        bedroom: {
          title: "Спальня",
          hfov: 150,
          pitch: -2.247,
          yaw: -173.819,
          type: "equirectangular",
          panorama: "bedroom.jpg",
          hotSpots: [
            {
              pitch: -2.247,
              yaw: -173.819,
              type: "scene",
              text: "Ванная комната",
              sceneId: "bath",
            },
            {
              pitch: -7.745,
              yaw: 202.48,
              type: "scene",
              text: "Гардероб",
              sceneId: "closet",
            },
            {
              pitch: -5.45,
              yaw: 72.14,
              type: "scene",
              text: "Кухня - Гостинная",
              sceneId: "hall",
            },
          ],
        },
        closet: {
          title: "Гардероб",
          hfov: 150,
          pitch: -2.247,
          yaw: -173.819,
          type: "equirectangular",
          panorama: "closet.jpg",
          hotSpots: [
            {
              pitch: 1.36,
              yaw: -101.6,
              type: "scene",
              text: "Ванная комната",
              sceneId: "bath",
            },
            {
              pitch: -1.584,
              yaw: -222.59,
              type: "scene",
              text: "Письменный стол",
              sceneId: "bedroom",
            },
            {
              pitch: 0.247,
              yaw: -206.5,
              type: "scene",
              text: "Кухня - Гостинная",
              sceneId: "hall",
            },
          ],
        },
        door: {
          title: "Вход в коттедж",
          hfov: 150,
          pitch: 7.163,
          yaw: 22.136,
          type: "equirectangular",
          panorama: "door.jpg",
          hotSpots: [
            {
              pitch: 9.298,
              yaw: -9.439,
              type: "scene",
              text: "Душевая комната",
              sceneId: "wc",
            },
            {
              pitch: 4.64,
              yaw: -43.08,
              type: "scene",
              text: "Кухня - Гостинная",
              sceneId: "hall",
            },
            {
              pitch: 2.306,
              yaw: -196.34,
              type: "scene",
              text: "Улица",
              sceneId: "mangal",
            },
          ],
        },
        balcony: {
          title: "Балкон",
          hfov: 150,
          pitch: 2.399,
          yaw: -27.9,
          type: "equirectangular",
          panorama: "balcony.jpg",
          hotSpots: [
            {
              pitch: -1.75,
              yaw: -35.6,
              type: "scene",
              text: "Уличный стол",
              sceneId: "balcony_table",
            },
            {
              pitch: 8.373,
              yaw: 91.01,
              type: "scene",
              text: "Кухня - Гостинная",
              sceneId: "hall",
            },
          ],
        },
        stairs: {
          title: "Второй этаж",
          hfov: 150,
          pitch: 6.14,
          yaw: -149.74,
          type: "equirectangular",
          panorama: "stairs.jpg",
          hotSpots: [
            {
              pitch: 1.069,
              yaw: -194.56,
              type: "scene",
              text: "Спальня",
              sceneId: "bedroom",
            },
            {
              pitch: -1.258,
              yaw: -139.15,
              type: "scene",
              text: "Гостинная",
              sceneId: "hall",
            },
            {
              pitch: -1.09,
              yaw: -78.577,
              type: "scene",
              text: "Туалет",
              sceneId: "wc",
            },
            {
              pitch: -28.083,
              yaw: -261.12,
              type: "scene",
              text: "Первый этаж - Кухня",
              sceneId: "room",
            },
          ],
        },
        bath: {
          title: "Ванная комната",
          hfov: 150,
          pitch: -0.1333,
          yaw: -189.96,
          type: "equirectangular",
          panorama: "bath.jpg",
          hotSpots: [
            {
              pitch: -2.612,
              yaw: -242.07,
              type: "scene",
              text: "Спальня",
              sceneId: "closet",
            },
            {
              pitch: 0.0289,
              yaw: -194.06,
              type: "scene",
              text: "Сауна",
              sceneId: "sauna",
            },
          ],
        },
        wc: {
          title: "Душевая комната",
          hfov: 150,
          pitch: -4.787,
          yaw: -342.3,
          type: "equirectangular",
          panorama: "wc.jpg",
          hotSpots: [
            {
              pitch: -4.787,
              yaw: -342.3,
              type: "scene",
              text: "Прихожая",
              sceneId: "door",
            },
          ],
        },
        sauna: {
          title: "Ванная комната",
          hfov: 150,
          pitch: -8.0,
          yaw: -159.0,
          type: "equirectangular",
          panorama: "sauna.jpg",
          hotSpots: [
            {
              pitch: -8.0,
              yaw: -159.0,
              type: "scene",
              text: "Ванная комната",
              sceneId: "bath",
            },
          ],
        },
        mangal: {
          title: "Ванная комната",
          hfov: 150,
          pitch: 5.586,
          yaw: 162.45,
          type: "equirectangular",
          panorama: "mangal.jpg",
          hotSpots: [
            {
              pitch: 9.932,
              yaw: 156.346,
              type: "scene",
              text: "Терасса",
              sceneId: "balcony_mangal",
            },
            {
              pitch: 2.4523,
              yaw: 51.47519,
              type: "scene",
              text: "Прихожая",
              sceneId: "door",
            },
          ],
        },
        balcony_mangal: {
          title: "Терасса",
          hfov: 150,
          pitch: -4.217,
          yaw: 18.89,
          type: "equirectangular",
          panorama: "balcony-mangal.jpg",
          hotSpots: [
            {
              pitch: -4.698,
              yaw: -106.847,
              type: "scene",
              text: "Терасса",
              sceneId: "mangal",
            },
            {
              pitch: 4.142,
              yaw: -8.997,
              type: "scene",
              text: "Уличный стол",
              sceneId: "balcony_table",
            },
          ],
        },
        balcony_table: {
          title: "Терасса",
          hfov: 150,
          pitch: -3.63,
          yaw: -99.1,
          type: "equirectangular",
          panorama: "balcony-table.jpg",
          hotSpots: [
            {
              pitch: -12.014,
              yaw: 74.79,
              type: "scene",
              text: "Терасса",
              sceneId: "balcony_mangal",
            },
            {
              pitch: -1.819,
              yaw: 235.12,
              type: "scene",
              text: "Кухная - Гостинная",
              sceneId: "hall",
            },
          ],
        },
      },
    };
  });
};
