export const terrasaVR = () => {
  return useState("terrasaVR", () => {
    return {
      default: {
        firstScene: "enter",
        author: "Veresk.club",
        sceneFadeDuration: 1000,
        autoRotate: 1,
        autoRotateInactivityDelay: 10000,
        autoLoad: true,
        compass: false,
        basePath: "/panoramas/terassa/",
        // hotSpotDebug: true,
      },
      scenes: {
        enter: {
          title: "Вход в шатер",
          hfov: 110,
          pitch: -1.418,
          yaw: 212.26,
          type: "equirectangular",
          panorama: "enter.jpg",
          hotSpots: [
            {
              pitch: 0.0414,
              yaw: 159.364,
              type: "scene",
              text: "Шатер",
              sceneId: "room",
            },
            {
              pitch: -1.418,
              yaw: 212.26,
              type: "scene",
              text: "Терраса",
              sceneId: "t_center",
            },
          ],
        },
        corner: {
          title: "Терраса вид на озеро",
          hfov: 110,
          pitch: -3,
          yaw: 150,
          type: "equirectangular",
          panorama: "terassa-corner.jpg",
          hotSpots: [
            {
              pitch: -2.6,
              yaw: 7.2,
              type: "scene",
              text: "Вход в шатер",
              sceneId: "enter",
            },
            {
              pitch: 0,
              yaw: 72,
              type: "scene",
              text: "Терраса вид на ресторан",
              sceneId: "far",
            },
            {
              pitch: -4.7,
              yaw: 118,
              type: "scene",
              text: "Шатры на крыше",
              sceneId: "roof",
            },
          ],
        },
        far: {
          title: "Терраса вид ресторан",
          hfov: 110,
          pitch: -3,
          yaw: 150,
          type: "equirectangular",
          panorama: "terassa-far.jpg",
          hotSpots: [
            {
              pitch: -11,
              yaw: 155,
              type: "scene",
              text: "Шатры на крыше",
              sceneId: "roof",
            },
            {
              pitch: -2.8,
              yaw: -111,
              type: "scene",
              text: "Терраса вид на озеро",
              sceneId: "corner",
            },
          ],
        },

        kitchen: {
          title: "Кухня",
          hfov: 130,
          pitch: -32.956,
          yaw: 237.46,
          type: "equirectangular",
          panorama: "tea.jpg",
          hotSpots: [
            {
              pitch: -8.99,
              yaw: 198.531,
              type: "scene",
              text: "Шатер",
              sceneId: "room",
            },
          ],
        },
        room: {
          title: "Шатер",
          hfov: 130,
          pitch: -9.194,
          yaw: -0.873,
          type: "equirectangular",
          panorama: "room.jpg",
          hotSpots: [
            {
              pitch: -1.628,
              yaw: -30.814,
              type: "scene",
              text: "Душевая комната",
              sceneId: "shower",
            },
            {
              pitch: -0.762,
              yaw: 26.296,
              type: "scene",
              text: "Кухня",
              sceneId: "kitchen",
            },
            {
              pitch: -2.6902,
              yaw: 167.801,
              type: "scene",
              text: "Вход в шатер",
              sceneId: "enter",
            },
            {
              pitch: -7.528,
              yaw: 120.123,
              type: "scene",
              text: "Обеденный стол",
              sceneId: "table",
            },
          ],
        },
        table: {
          title: "Обеденный стол",
          hfov: 130,
          pitch: -5.3885,
          yaw: -141.117,
          type: "equirectangular",
          panorama: "table.jpg",
          hotSpots: [
            {
              pitch: 0.959,
              yaw: -149.628,
              type: "scene",
              text: "Душевая комната",
              sceneId: "shower",
            },
            {
              pitch: 1.5413,
              yaw: -115.356,
              type: "scene",
              text: "Кухня",
              sceneId: "kitchen",
            },
            {
              pitch: -14.373,
              yaw: -252.637,
              type: "scene",
              text: "Вход в шатер",
              sceneId: "enter",
              targetPitch: 9.3,
              targetYaw: 1.61,
            },
            {
              pitch: -18.079,
              yaw: -165.734,
              type: "scene",
              text: "Шатер",
              sceneId: "room",
            },
          ],
        },
        shower: {
          title: "Душевая комната",
          hfov: 130,
          pitch: 3.425,
          yaw: 108.26,
          type: "equirectangular",
          panorama: "shower.jpg",
          hotSpots: [
            {
              pitch: 6.158,
              yaw: 265.8,
              type: "scene",
              text: "Шатер",
              sceneId: "room",
            },
          ],
        },
        t_center: {
          title: "Терраса центр",
          hfov: 130,
          pitch: 8.922,
          yaw: -85.927,
          type: "equirectangular",
          panorama: "terassa-center.jpg",
          hotSpots: [
            {
              pitch: 1.548,
              yaw: -303.9,
              type: "scene",
              text: "Вход в Шатер",
              sceneId: "enter",
            },
            {
              pitch: 8.922,
              yaw: -85.927,
              type: "scene",
              text: "Вид на Озеро",
              sceneId: "t_lake",
            },
          ],
        },
        t_lake: {
          title: "Вид на озеро",
          hfov: 130,
          pitch: -12.581,
          yaw: 10.854,
          type: "equirectangular",
          panorama: "terassa-lake.jpg",
          hotSpots: [
            {
              pitch: -1.7274,
              yaw: -194.406,
              type: "scene",
              text: "Терраса центр",
              sceneId: "t_center",
              targetPitch: 3.184,
              targetYaw: 3.184,
            },
            {
              pitch: -0.8244,
              yaw: -86.08,
              type: "scene",
              text: "Вид на Ресторан",
              sceneId: "t_rest",
            },
            {
              pitch: -10.7685,
              yaw: -23.73,
              type: "scene",
              text: "Шатры на Крыше",
              sceneId: "roof",
            },
          ],
        },
        t_rest: {
          title: "Вид на Ресторан",
          hfov: 130,
          pitch: -17.691,
          yaw: 25.846,
          type: "equirectangular",
          panorama: "terassa-left.jpg",
          hotSpots: [
            {
              pitch: -2.665,
              yaw: 124.028,
              type: "scene",
              text: "Терраса центр",
              sceneId: "t_center",
              targetPitch: 3.184,
              targetYaw: 3.184,
            },
            {
              pitch: -4.339,
              yaw: 75.664,
              type: "scene",
              text: "Вид на Озеро",
              sceneId: "t_lake",
            },
            {
              pitch: -13.968,
              yaw: -25.036,
              type: "scene",
              text: "Шатры на Крыше",
              sceneId: "roof",
            },
          ],
        },
        roof: {
          title: "Шатры на крыше",
          hfov: 130,
          pitch: -4.896,
          yaw: 0.793,
          type: "equirectangular",
          panorama: "roof-right.jpg",
          hotSpots: [
            {
              pitch: 8.152,
              yaw: -176.86,
              type: "scene",
              text: "Шатры на терассе",
              sceneId: "t_lake",
            },
            {
              pitch: -2.952,
              yaw: -47.626,
              type: "scene",
              text: "Вид на озеро",
              sceneId: "roofCenter",
            },
          ],
        },
        roofCenter: {
          title: "Шатры на крыше",
          hfov: 120,
          pitch: 1.303,
          yaw: 177.45,
          type: "equirectangular",
          panorama: "roof-center.jpg",
          hotSpots: [
            {
              pitch: -10.837,
              yaw: 70.991,
              type: "scene",
              text: "Камин на крыше",
              sceneId: "roof_fire",
            },
            {
              pitch: -3.475,
              yaw: 88.847,
              type: "scene",
              text: "Вид на паркинг",
              sceneId: "roof_parking",
            },
            {
              pitch: -4.678,
              yaw: 271.85,
              type: "scene",
              text: "Шатры на крыше",
              sceneId: "roof",
              targetPitch: -4.89,
              targetYaw: -152.927,
            },
          ],
        },
        roof_fire: {
          title: "Камин на крыше",
          hfov: 120,
          pitch: 2.564,
          yaw: 12.452,
          type: "equirectangular",
          panorama: "roof-fire.jpg",
          hotSpots: [
            {
              pitch: 1.074,
              yaw: 74.352,
              type: "scene",
              text: "Шатры на крыше",
              sceneId: "roof",
              targetPitch: -4.89,
              targetYaw: -152.927,
            },
            {
              pitch: -0.498,
              yaw: -52.304,
              type: "scene",
              text: "Вид на паркинг",
              sceneId: "roof_parking",
            },
          ],
        },
        roof_parking: {
          title: "Вид на паркинг",
          hfov: 120,
          pitch: -3,
          yaw: 294.39,
          type: "equirectangular",
          panorama: "roof-left.jpg",
          hotSpots: [
            {
              pitch: -11.4311,
              yaw: 101.06,
              type: "scene",
              text: "Камин на крыше",
              sceneId: "roof_fire",
            },
            {
              pitch: -0.4465,
              yaw: 90.983,
              type: "scene",
              text: "Вид на озеро",
              sceneId: "roofCenter",
            },
          ],
        },
      },
    };
  });
};
