export const sibiryakovRoomsData = () => {
	return useState("sibiryakovRoomsData", () => [
		{
			title: "Делюкс",
			slug: "delux",
			params: { s: "40", rooms: "1", guests: "3" },
			images: ["/images/occupation/sibiryakov/delux/delux-card.jpeg"],
			tl: { room: 329454, hotel: 53273 },
			info: {
				price: 19000,
				link: "/hotel/delux",
				bookLink: "/",
				type: "sibiryakov",
				description: `Отель расположен на первой береговой линии — до пляжа рукой подать. Каждый вечер гостей ждут потрясающие закаты над озером. Здесь легко забыть о суете и просто наслаждаться моментом. Это по‑настоящему прекрасное место для перезагрузки.`,
			},
			slideShow: [
				{ src: "/images/occupation/sibiryakov/delux/slides/delux-1.jpeg" },
				{ src: "/images/occupation/sibiryakov/delux/slides/delux-2.jpeg" },
				{ src: "/images/occupation/sibiryakov/delux/slides/delux-3.jpeg" },
				{ src: "/images/occupation/sibiryakov/delux/slides/delux-4.jpeg" },
				{ src: "/images/occupation/sibiryakov/delux/slides/delux-5.jpeg" },
				{ src: "/images/occupation/sibiryakov/delux/slides/delux-6.jpeg" },
				{ src: "/images/occupation/sibiryakov/delux/slides/delux-7.jpeg" },
			],
			features: ["wifi", "air-conditioner", "vault", "kingsize-bed"],
		},
		{
			title: "Люкс",
			slug: "lux",
			params: { s: "50", rooms: "1", guests: "2" },
			images: ["/images/occupation/sibiryakov/lux/lux-card.jpeg"],
			tl: { room: 329453, hotel: 53273 },
			info: {
				price: 21800,
				link: "/hotel/lux",
				bookLink: "/",
				type: "sibiryakov",
				description: `основной фонд отеля, где продуман каждый сантиметр пространства.`,
			},
			slideShow: [
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-1.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-2.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-3.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-4.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-5.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-6.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-7.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-8.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-9.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-10.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-11.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-11.jpeg" },
				{ src: "/images/occupation/sibiryakov/lux/slides/lux-13.jpeg" },
			],
			features: ["wifi", "air-conditioner", "vault", "kingsize-bed"],
		},
		{
			title: "Сьют",
			slug: "sibiryakov-suit",
			params: { s: "75", rooms: "2", guests: "4" },
			images: ["/images/occupation/sibiryakov/suit/suit-card.jpeg"],
			tl: { room: 329453, hotel: 53273 },
			info: {
				price: 40950,
				link: "/hotel/sibiryakov-suit",
				bookLink: "/",
				type: "sibiryakov",
				description: `номера с богатым интерьером и камином: для тех, кто хочет максимального комфорта и атмосферы.`,
			},
			slideShow: [
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-1.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-2.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-3.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-4.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-5.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-6.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-7.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-8.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-9.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-10.jpeg" },
				{ src: "/images/occupation/sibiryakov/suit/slides/suit-11.jpeg" },
			],
			features: ["wifi", "air-conditioner", "vault", "kingsize-bed"],
		},
	]);
};
